### ISSUE TITLE
full backup disk

### ISSUE THREAD

**Issue by lotharschulz** [zalando/ghe-backup#44]
```
root@....:/data/ghe-production-data# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf       985G  985G     0 100% /data
```

lets reduce the number of backups

**Comment by lotharschulz** [comment]
https://github.com/zalando/ghe-backup/pull/45 merged

**Comment by lotharschulz** [comment]
trigger new deployment, will free up disk by deleting older backups to have space available for new backup attempt

**Comment by lotharschulz** [comment]
```20170221T171301``` backup is started. wait for this to be completed (~80G available on /data should be enough)

**Comment by lotharschulz** [comment]
redeploy attempt failed:
```
Feb 21 20:25:46 ip-172-31-138-151 taupage-init: INFO: Attached EBS volume 'ghe-backup-volume2' as '/dev/sdf'
Feb 21 20:25:46 ip-172-31-138-151 taupage-init: INFO: /dev/xvdf: erase_on_boot=False, erase_tag_set=False
Feb 21 20:25:46 ip-172-31-138-151 taupage-init: INFO: Waiting for /dev/xvdf to stabilize..
Feb 21 20:25:47 ip-172-31-138-151 kernel: [   45.944970] blkfront: xvdf: barrier or flush: disabled; persistent grants: disabled; indirect descriptors: enabled;
Feb 21 20:25:47 ip-172-31-138-151 kernel: [   45.948950]  xvdf: unknown partition table
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: ERROR: Operational error /dev/xvdf.
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: Traceback (most recent call last):
Feb 21 20:25:51 ip-172-31-138-151 taupage-init:   File "./init.d/10-prepare-disks.py", line 124, in check_partition
Feb 21 20:25:51 ip-172-31-138-151 taupage-init:     call_command(call)
Feb 21 20:25:51 ip-172-31-138-151 taupage-init:   File "./init.d/10-prepare-disks.py", line 98, in call_command
Feb 21 20:25:51 ip-172-31-138-151 taupage-init:     raise CmdException(proc.returncode, stderr.decode('utf-8'))
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: CmdException: Command returned non-zero exit status 8:
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: e2fsck: Can't allocate 160258200 bytes for directory map
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: 
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: e2fsck: aborted
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: 
Feb 21 20:25:51 ip-172-31-138-151 taupage-init: ERROR: Failed to start 10-prepare-disks.py
```
(https://github.com/zalando-stups/taupage/blob/master/runtime/opt/taupage/init.d/10-prepare-disks.py#L135)
Looks like the former full disk caused the issue above.

**Comment by lotharschulz** [comment]
new volume created, initialised and attached:
```
root@08af65be79f8:/backup# cd /data/
root@08af65be79f8:/data# ls
lost+found
```

**Comment by lotharschulz** [comment]
backup attempt started manually:

```
root@xxxx:/data# /backup/backup-utils/bin/ghe-backup -v
Creating the backup data directory ...
Starting backup of gh.xus.zalando.de in snapshot 20170221T212602
Connect gh.xus.zalando.de:122 OK (v2.8.7)
Backing up GitHub settings ...
* Transferring settings data ...
* Transferring license data ...
* Transferring management console password ...
* Transferring SAML keys ...
* Transferring UUID ...
Backing up SSH authorized keys ...
Backing up SSH host keys ...
Backing up MySQL database ...
Backing up Redis database ...
Backing up audit log ...
Backing up hookshot logs ...
Backing up Git repositories ...

* Transferring auxiliary files ...
receiving incremental file list
./
0/
0/00/
0/00/99/
0/00/99/c6/
0/00/99/c6/gist/
0/00/99/c6/gist/9a9dd7f3c192dfaf4xxx.git/
...
```

**Comment by lotharschulz** [comment]
```
root@.......:/backup# ll /data/ghe-production-data             
....
drwxr-xr-x 6 root root 4096 Feb 21 21:32 20170221T212602/
```
